### ISSUE TITLE
Claude crash: "claude will return soon"

### ISSUE THREAD

**Issue by chaorders1** [g0t4/mcp-server-commands#2]
![image](https://github.com/user-attachments/assets/e7c6c729-8a19-402a-b0b6-d2095dae2cfe)

Have this issue. Not sure it is claude or this mcp. Also see this error when using server-filesystem provided by claude

**Comment by g0t4** [comment]
I suspect it's the Claude service overwhelmed, I've had a lot of notices about defaulting to Concise mode due to volume of traffic. Can you check your MCP logs?

`~/Library/Logs/Claude/mcp.log`

**Comment by g0t4** [comment]
FYI I published version `0.4` with logging to `~/Library/Logs/Claude/mcp-server-mcp-server-commands.log`... more details in README.md

**Comment by g0t4** [comment]
I'm going to close this issue for now, if you still have issues, please reopen it. Happy to help
